In [1]:
import numpy as np
np.__version__

'1.26.4'

In [2]:
arr=np.array([1,2,3,3,4])

In [3]:
print(arr)

[1 2 3 3 4]


In [5]:
print(arr.dtype)

int32


In [6]:
arr1=np.array([1.2,3.4])
print(arr1.dtype)

float64


In [7]:
arr2=np.array([True,False])
print(arr2.dtype)

bool


In [8]:
arr3=np.array([3+4j,5j])
print(arr3.dtype)

complex128


In [9]:
arr4=np.array(['bharath','chintu'])
print(arr4.dtype)

<U7


In [10]:
arr5=np.array([1,2,3.9,'z',{1,2,3}]) 
print(arr5.dtype)#-->Object 

object


In [12]:
#1-D Array 
a1=np.array([1,2,3,4]) 
#2-D Array 
a2=np.array([[1,2,3], 
[4,5,6]]) 
#3-D Array 
a3=np.array([[[1,2,3], 
[4,5,6]], 
[[7,8,9], 
[10,11,12]]]) 


In [13]:
# ndim is an attribute ,it return the number of dimensions of an array
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [14]:
#shape is an attribute,it return the shape of an array in the form of tuple
# 1-d=returns len of array
# 2-d =returns no.of rows and cols
# 3-d retuurn no.of slices,rows and cols

print(a1.shape)
print(a2.shape)
print(a3.shape)

(4,)
(2, 3)
(2, 2, 3)


In [17]:
#reshape()-> is a function,used to change the rows and col in existing array
#note-> the product of no.of rows and colums should be equal to the no.of values present in
#the array
print(a2.reshape(3,2))
print(a3.reshape(3,2,2))

[[1 2]
 [3 4]
 [5 6]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [19]:
# flatten is a method which is used to convert multi dimensional array to uni dimensional array

print(a2.flatten())
print(a3.flatten())

[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [28]:
#ndmin-> is a parameter ,it will convert uni dimensional array to multi dimensional array
# we have to give this ndmin at the time of array creation
a4=np.array([1,2,3,4,5],ndmin=2)
print(a4)
print(a4.ndim)
a5=np.array([1,2,3,4,5,6,7,8,9],ndmin=5)
print(a5)
print(a5.ndim)

[[1 2 3 4 5]]
2
[[[[[1 2 3 4 5 6 7 8 9]]]]]
5


In [29]:
#arange() 
#it is a function which is present inside the Numpy library 
#it is used to generate sequence of the numbers b/w the specified limits 
a6=np.arange(1,10,1)

In [30]:
print(a6)

[1 2 3 4 5 6 7 8 9]


In [36]:
a7=np.arange(-1,-10,-1)
print(a7)

[-1 -2 -3 -4 -5 -6 -7 -8 -9]


In [38]:
a8=np.linspace(1,10)
print(a8)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [40]:
aa1=np.random.randint(1,10,5)
print(aa1)
aa2=np.random.randint(1,10,(2,3))
print(aa2)
aa3=np.random.randint(1,10,(2,3,3))
print(aa3)

[1 6 8 8 5]
[[6 8 9]
 [5 4 9]]
[[[1 2 3]
  [8 1 6]
  [1 1 1]]

 [[8 2 1]
  [9 7 9]
  [2 3 2]]]


In [41]:
ab1=np.random.rand(10)
print(ab1)
ab2=np.random.rand(2,3)
print(ab2)
ab3=np.random.rand(2,3,3)
print(ab3)

[0.93470529 0.96150281 0.08846238 0.00115457 0.81569961 0.36150073
 0.06575994 0.08003061 0.86843398 0.74249746]
[[0.6650758  0.30627768 0.33006551]
 [0.83226845 0.76432509 0.74011338]]
[[[0.24348592 0.06137384 0.63059465]
  [0.74902583 0.83726484 0.29525887]
  [0.12664237 0.86567261 0.99487958]]

 [[0.61503058 0.5154202  0.70480665]
  [0.81010107 0.58534096 0.06711104]
  [0.49032525 0.83556733 0.26541424]]]


In [44]:
ab11=np.random.randn(10)
print(ab11)
ab22=np.random.randn(2,3)
print(ab22)
ab33=np.random.randn(2,3,3)
print(ab33)
print(ab33.dtype)

[ 0.29429321  0.11740185 -0.07294547 -0.85246675 -1.5520935   1.32826836
  2.22532841 -0.33085119 -0.78170533  0.55559631]
[[-0.44748443  1.14387078 -0.71543883]
 [ 1.08953344  0.37662659  0.24019723]]
[[[-0.38699261 -0.08562925  0.30924794]
  [-0.25837283 -0.29595849 -1.11291063]
  [-0.97845907 -0.58049202 -0.71604899]]

 [[-0.2709454   2.41142349  1.08277384]
  [ 0.47835656 -0.68226861  0.47402756]
  [ 1.27197569 -1.72733856  0.50566663]]]
float64


In [46]:
print(np.random.choice(ab11))

-1.5520934953244039


In [47]:
print(np.random.choice(ab33))

ValueError: a must be 1-dimensional

In [52]:
aa11=np.array([1,2,3,4])
print(aa11)
print(np.random.shuffle(aa11))
print(aa11)
np.random.shuffle(ab33)
print(ab33)

[1 2 3 4]
None
[2 1 4 3]
[[[-0.2709454   2.41142349  1.08277384]
  [ 0.47835656 -0.68226861  0.47402756]
  [ 1.27197569 -1.72733856  0.50566663]]

 [[-0.38699261 -0.08562925  0.30924794]
  [-0.25837283 -0.29595849 -1.11291063]
  [-0.97845907 -0.58049202 -0.71604899]]]


In [53]:
aa22=aa11.copy()
print(aa22)

[2 1 4 3]


In [59]:
array=np.array([1,2,3,4,5])
array2=array.view()

print(array*4)
print(array2)

[ 4  8 12 16 20]
[1 2 3 4 5]


In [60]:
print(id(array))

1198034164912


In [66]:
print(array.ctypes.data)

1197953145584


In [65]:
a=np.array([1,2,3]) 
b=a 
print(a) 
print(b) 
print('var address') 
print(id(a)) 
print(id(b)) 
print('val address') 
print(a.ctypes.data) 
print(b.ctypes.data)

[1 2 3]
[1 2 3]
var address
1198033890224
1198033890224
val address
1197953143824
1197953143824


In [71]:

zero_array1=np.zeros(10,dtype=int)
print(zero_array1)
zero_array2=np.zeros((2,3),dtype=int)
print(zero_array2)
zero_array3=np.zeros((2,3,3),dtype=int)
print(zero_array3)

[0 0 0 0 0 0 0 0 0 0]
[[0 0 0]
 [0 0 0]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [73]:
ones_array1=np.ones(10,dtype=int)
print(ones_array1)
ones_array2=np.ones((2,3),dtype=int)
print(ones_array2)
ones_array3=np.ones((2,3,3),dtype=int)
print(ones_array3)

[1 1 1 1 1 1 1 1 1 1]
[[1 1 1]
 [1 1 1]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [77]:
print(ones_array1[3])

1


In [80]:
print(ab22[1][2])

-0.7154388270633208


In [81]:
print(ab33[1][2][1])

-0.5804920156058876
